apiVersion: v1
# Indicates this as a service
kind: Service
metadata:
 # Service name
 name: mon-app-deployment
spec:
 selector:
   # Selector for Pods
   app: mon-app
 ports:
   # Port Map
 - port: 80
   targetPort: 80
   protocol: TCP
 type: LoadBalancer