apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: 2048-game
  name: game
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: 2048-game
  template:
    metadata:
      labels:
        app.kubernetes.io/name: 2048-game
    spec:
      containers:
      - image: alexwhen/docker-2048
        name: game
        ports:
        - containerPort: 80
