- hosts: manager
  become_user: group4
  tasks:
    - name: Etape 1
      command:
        cmd:  kubectl create deploy game --image=alexwhen/docker-2048
        
    - name: Etape 2
      command: 
        cmd: kubectl scale --replicas=2 deploy/game
        
    - name: Etape 3
      command:
        cmd: kubectl expose deploy game --type=LoadBalancer --port 80 --target-port=80  
