- hosts: manager
  become_user: group4
  tasks:
    - name: 2048 Deployment replicated
      command:
        cmd: kubectl apply -f /home/manager/2048_deployment_replicated.yaml

    - name: Expose service 2048
      command:
        cmd: kubectl expose deploy game --type=LoadBalancer --port 80 --target-port=80
