---
- name: Dépoloyer l'application 2048
  hosts: manager
  tasks:
    - name: Cloner le référentiel
      git:
        repo: https://github.com/cedric69lt/Groupe-4_Brief-15
        dest: /home/app
        version: main

- name: Déploiement de l'application sur Kubernetes
  hosts: manager
  tasks:
    - name: Appliquer le fichier de déploiement
      command: kubectl apply -f /home/app/deployment.yml

- name: Déploiement du service
  hosts: manager
  tasks:
    - name: Appliquer le fichier système
      command: kubectl apply -f /home/app/service.yml
